### ISSUE TITLE
Script appears to find opusenc binary but still crashes

### ISSUE THREAD

**Issue by ananaso** [ZivaVatra/flac2all#36] opened 2018-12-01 22:20 UTC
I just tried to run flac2all but ran into the following issue:

> opusenc ist /usr/bin/opusenc
> Traceback (most recent call last):
>   File "/usr/bin/flac2all", line 839, in <module>
>     opusClass = opus()
>   File "/usr/bin/flac2all", line 110, in __init__
>     data = re.search("\d\.\d\.\d",data).group(0)
> AttributeError: 'NoneType' object has no attribute 'group'

Looking at previous issues reported, it seems this would be an issue with opusenc not being installed properly. However, the script reports the existence of opusenc correctly - as seen above - and I confirmed it through my package manager and by going to the location of the binary myself.

Once I commented all the code relating to opus out of the script it ran correctly and converted my files (to mp3). Upon further investigation I've found that explicitly defining the path for my opusenc binary as the script recommends solves the issue. I still feel like this is a bug though, since the error from above clearly output the path to the binary correctly, but I'll leave that for someone more knowledgeable to determine.

I'm running the following software:
Arch Linux, kernel 4.19.4
opusenc opus-tools 0.2 (using libopus 1.3)
flac2all v3 (top of script) v2.75-4 (AUR)
python 2.7.15

**Comment by ZivaVatra** [comment] 2018-12-02 14:16
Hi Ananaso,

This sounds like a duplicate of issue https://github.com/ZivaVatra/flac2all/issues/25  which was fixed back in 2015. Can you reproduce the bug if you use the latest v3 version from git?

If it is fixed in the latest version, then the package maintainer needs to update the AUR package.

**Comment by ananaso** [comment] 2018-12-07 01:59
Oops, didn't realize the package was out of date on the AUR (and figured it wasn't the same problem since the last one was reported in 2015) - apologies!
It does indeed work, thanks for the great tool!

**Closed** 2018-12-07 02:00 UTC
Labels: duplicate
